### PR TITLE
add dark theme and workaround for locale bug

### PR DESCRIPTION
**Pull request by xarbit**
added entrypoint script to workaround some things and issues between flatpak and upstream prusaslicer.

There is now a sorta fallback to LC_ALL=en_US.UTF-8 when the default execution fails and not detecting the locale, this workaround should prevent the application from crashing and from not starting up when that mixed locale issue gets screwed up. 
Note: running the flatpak application from the terminal with `flatpak run com.prusa....` can still fail as it does not use the entrypoint script, but this known and will be adressed in the future.

So basicly this workaround solves the following issue (at least I hope for the time beeing, on the 2.4.x release until we can find a better solution).

https://github.com/flathub/com.prusa3d.PrusaSlicer/issues/27  

The dark variant/theme is set being default and it can be controlled by the custom environment variable: 

`--env=PRUSA_SLICER_DARK_THEME=true`

If the dark theme is not wanted and totally hated, dont worry you can override the PRUSA_SLICER_DARK_THEME to any other value other then true overriding with Command-line or flatseal. 

This implementation of the dark variant uses GTK_THEME=Adwaita:dark and some hacky little script I borrowed from flathub/com.spotify.Client and adjusted a bit to work here, it changes the window border to dark under X11.
 
 
image

### CODE REVIEW

**Comment by tamasmeszaros** [comment]
Hello @xarbit ! I see that you've put some effort into forcing the adwaita-dark theme. Finding the env var will take some time for an average user who wants the light theme back. This is also a different policy from what the upstream implements. Is there a good reason for this workaround other than personal preference?

**Comment by tamasmeszaros** [comment]
I don't know if this has been observed yet, but if you do `flatpak install --reinstall org.freedesktop.Platform.Locale`, the crashes will go away. All the platform locales will be installed in Flatpak land.

**Comment by xarbit** [comment]
@tamasmeszaros thanks.. the reason for the dark theme was because of the default font color and the better appealing. 
And because windows and macOS have it too :).
Don't worry, the default will be reverted when official released and made optional. I was planning to work on the code and push upstream to get it official including the support for gcode and 3mf mime files with icons. 

For the languages, you need to change it in gnome settings and do a flatpak update. It will then download the language files that are missing.

I am also getting some documentation ready for prusa upstream wiki.

**Comment by xarbit** [comment]
To note.. the language was never the reason for the crashes. 
Before they where not split and always there. I only reworked it the flatpak way. The crashes mostly appeared when using mixed locale for language and measurements.

**Comment by xarbit** [comment]
@tamasmeszaros I set it optional 
https://github.com/flathub/com.prusa3d.PrusaSlicer/pull/38/commits/3ef949ba5ddd5c42e452387287011905fce0c086

**Comment by xarbit** [comment]
@tamasmeszaros see this issue for more information: https://github.com/flathub/com.prusa3d.PrusaSlicer/issues/27

**Comment by tamasmeszaros** [comment]
Hi @xarbit, ok with the dark theme, I trust your judgement :) . 

That is strange, if the crashes were present when all the locales were installed. Just for the record, what I've found is that the crash (well it is a handled exception and a manual exit() call) is due to a `boost::nowide::nowide_filesystem()` call in PrusaSlicer.cpp which in turn calls `boost::filesystem::path::imbue()`. I've looked into the boost source code, and the function comments state the possibility of throwing an exception on Linux if the system locales are screwed up. For some reason, it needs to initialize the complete system locale only on Linux. So there is not much you can do other than catch the exception and exit the app. If I tried to ignore that exception, the app crashed at some point in the initialization.

**Pull request merged**
