### PR TITLE
update to version 2.3.0

### LINKED ISSUE #7: Version 2.3?
Just wondering when version 2.3 will show up in flatpack hub?

### PR DESCRIPTION
**Pull request by ctron**
This also switches to GTK3, as GTK2 seems to be no longer
working.

Closes #7

### CODE REVIEW

**Comment by vadyalex** [comment]
U r my hero, sir. Thank you! :rocket:

**Comment by gwutz** [comment]
Who is responsible to merge this? I did the update myself locally but i would appreciate this getting merged soon. Btw i also switched to GTK 3 :) I did the identical steps and can at least provide a LGTM

**Comment by ctron** [comment]
> Who is responsible to merge this? I did the update myself locally but i would appreciate this getting merged soon. Btw i also switched to GTK 3 :) I did the identical steps and can at least provide a LGTM

I think that would be @xarbit

**Comment by xarbit** [comment]
good job.. thanks.

**Pull request merged**
