### PR TITLE
Fix App Listing Quality on FlatHub

### PR DESCRIPTION
**Pull request by xarbit**
- fixes: Has primary brand colors
- fixes: Icon doesn't fill too much or too little of the canvas
- fixes: Summary, no weird formatting or punctuation

image

### CODE REVIEW

**Comment by xarbit** [comment]
@eliadevito can you please test this when you have time? 
This is to fix and implement the FlatHub guidelines, I need to know if you see any issues in the application icons. 

image

**Comment by xarbit** [comment]
Screenshot from 2024-06-30 15-55-43
Screenshot from 2024-06-30 16-11-32

**Comment by Riksu9000** [comment]
I was surprised to see a different icon, but it looks like it is based on the official mac icon.

**Comment by xarbit** [comment]
@Riksu9000  
Basically it is yes :-), I actually initially created the official mac icon for PrusaSlicer and reused it .. https://github.com/xarbit/PrusaSlicer-macOS-icons
But I am not satisfied with them, I still get issues for the App Listing Quality on flathub.

**Pull request merged**
