### PR TITLE
version bump to 2.5.0

### PR DESCRIPTION
**Pull request by BOFH90**

### CODE REVIEW

**Comment by tgmatt** [comment]
Looks like a transient build error. Any chance we could get this reviewed and merged?

**Comment by stephen304** [comment]
I took a shot at building locally and had to update some of the deps in the flatpak config so it would download updated deps and prevent cmake from trying to use the network in the sandboxed build environment (if I understand how that works correctly):

```diff
diff --git a/com.prusa3d.PrusaSlicer.yml b/com.prusa3d.PrusaSlicer.yml
index 136f1db..fa6c767 100755
--- a/com.prusa3d.PrusaSlicer.yml
+++ b/com.prusa3d.PrusaSlicer.yml
@@ -183,6 +183,12 @@ modules:
         dest: external-packages/CGAL
         sha256: c2b035bd078687b6d8c0fb6371a7443adcdb647856af9969532c4050cd5f48e5
 
+      # EXPAT
+      - type: file
+        url: https://github.com/libexpat/libexpat/archive/refs/tags/R_2_4_3.zip
+        dest: external-packages/EXPAT
+        sha256: 8851e199d763dc785277d6d414ed3e70ff683915158b51b8d8781df0e3af950a
+
       # GMP
       - type: file
         url: https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2
@@ -227,9 +233,9 @@ modules:
 
       # OpenVDB
       - type: file
-        url: https://github.com/tamasmeszaros/openvdb/archive/refs/tags/v6.2.1-prusa3d.zip
+        url: https://github.com/tamasmeszaros/openvdb/archive/a68fd58d0e2b85f01adeb8b13d7555183ab10aa5.zip
         dest: external-packages/OpenVDB
-        sha256: caf9f0c91976722883ff9cb32420ef142af22f7e625fc643b91c23d6e4172f62
+        sha256: f353e7b99bd0cbfc27ac9082de51acf32a8bc0b3e21ff9661ecca6f205ec1d81
 
       # PNG, libpng
       - type: file
@@ -245,9 +251,9 @@ modules:
 
       # TBB
       - type: file
-        url: https://github.com/wjakob/tbb/archive/a0dc9bf76d0120f917b641ed095360448cabc85b.tar.gz
+        url: https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.5.0.zip
         dest: external-packages/TBB
-        sha256: 0545cb6033bd1873fcae3ea304def720a380a88292726943ae3b9b207f322efe
+        sha256: 83ea786c964a384dd72534f9854b419716f412f9d43c0be88d41874763e7bb47
 
       # TIFF, libtiff
       - type: file
```

Though it still fails, this time with error 2 and a lot of messages that have something to do with openVDB:

```
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: ../libopenvdb.a(points.cc.o): in function `void tbb::detail::d1::small_object_allocator::deallocate<tbb::detail::d1::start_reduce<openvdb::v8_2::tree::LeafManager<openvdb::v8_2::tree::Tree<openvdb::v8_2::tree::RootNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::points::PointDataLeafNode<openvdb::v8_2::PointIndex<unsigned int, 1u>, 3u>, 4u>, 5u> > > const>::LeafRange, openvdb::v8_2::tree::LeafManager<openvdb::v8_2::tree::Tree<openvdb::v8_2::tree::RootNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::points::PointDataLeafNode<openvdb::v8_2::PointIndex<unsigned int, 1u>, 3u>, 4u>, 5u> > > const>::LeafReducer<openvdb::v8_2::tools::count_internal::ActiveVoxelCountOp<openvdb::v8_2::tree::Tree<openvdb::v8_2::tree::RootNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::points::PointDataLeafNode<openvdb::v8_2::PointIndex<unsigned int, 1u>, 3u>, 4u>, 5u> > > > >, tbb::detail::d1::auto_partitioner const> >(tbb::detail::d1::start_reduce<openvdb::v8_2::tree::LeafManager<openvdb::v8_2::tree::Tree<openvdb::v8_2::tree::RootNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::points::PointDataLeafNode<openvdb::v8_2::PointIndex<unsigned int, 1u>, 3u>, 4u>, 5u> > > const>::LeafRange, openvdb::v8_2::tree::LeafManager<openvdb::v8_2::tree::Tree<openvdb::v8_2::tree::RootNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::points::PointDataLeafNode<openvdb::v8_2::PointIndex<unsigned int, 1u>, 3u>, 4u>, 5u> > > const>::LeafReducer<openvdb::v8_2::tools::count_internal::ActiveVoxelCountOp<openvdb::v8_2::tree::Tree<openvdb::v8_2::tree::RootNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::tree::InternalNode<openvdb::v8_2::points::PointDataLeafNode<openvdb::v8_2::PointIndex<unsigned int, 1u>, 3u>, 4u>, 5u> > > > >, tbb::detail::d1::auto_partitioner const>*, tbb::detail::d1::execution_data const&)':
/run/build/PrusaSlicer/deps/build/destdir/usr/local/include/oneapi/tbb/detail/_small_object_pool.h:90: undefined reference to `tbb::detail::r1::deallocate(tbb::detail::d1::small_object_pool&, void*, unsigned long, tbb::detail::d1::execution_data const&)'
collect2: error: ld returned 1 exit status
make[6]: *** [openvdb/openvdb/cmd/CMakeFiles/vdb_print.dir/build.make:104: openvdb/openvdb/cmd/vdb_print] Error 1
make[5]: *** [CMakeFiles/Makefile2:169: openvdb/openvdb/cmd/CMakeFiles/vdb_print.dir/all] Error 2
make[4]: *** [Makefile:146: all] Error 2
make[3]: *** [CMakeFiles/dep_OpenVDB.dir/build.make:86: dep_OpenVDB-prefix/src/dep_OpenVDB-stamp/dep_OpenVDB-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:397: CMakeFiles/dep_OpenVDB.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:404: CMakeFiles/dep_OpenVDB.dir/rule] Error 2
make: *** [Makefile:267: dep_OpenVDB] Error 2
Error: module PrusaSlicer: Child process exited with code 2

```

I'm not sure if that's related to anything I missed in the dependencies or something unrelated completely

**Comment by xarbit** [comment]
Thanks for this and sorry that I have not updated PrusaSlicer on flat hub yet.

**Comment by xarbit** [comment]
Ill get to this hopefully soon, my linux box is broken.

**Comment by xarbit** [comment]
I am having issues with the build and I haven't figured out what the issue is yet.

**Comment by xarbit** [comment]
we have build that works, there was a problem with TBB and Prusa provided a new branch with a fix.
I will close this MR in favour for https://github.com/flathub/com.prusa3d.PrusaSlicer/pull/49.

See the issue : https://github.com/flathub/com.prusa3d.PrusaSlicer/issues/46

**Pull request closed without merging**
