### PR TITLE
WIP: Release 2.3.0

### PR DESCRIPTION
**Pull request by mamoit**

### CODE REVIEW

**Comment by mamoit** [comment]
Not as easy as I hoped :thinking:

**Comment by mamoit** [comment]
I can't get a successful build.

**Comment by xarbit** [comment]
I started working on this and to simplify everything ..

**Comment by mamoit** [comment]
During the weekend I tried to use the `deps` cmake that is in the prusaslicer repo itself to install the dependencies, instead of having to duplicate the effort with every release.
But it was taking almost 45min on each build and in the end there was always one missing lib here or there, so I gave up.
I can push my progress so far in about ~12h.
I'm not very experienced in flatpak building, I'm more of a docker/k8s person, and the flatpak-builder documentation is quite bad :/

**Pull request closed without merging**
