### PR TITLE
Fix crash with "Complete individual objects" (#55)

### PR DESCRIPTION
**Pull request by eliadevito**
test fix for bug #55

### CODE REVIEW

**Comment by eliadevito** [comment]
bot, build com.prusa3d.PrusaSlicer

**Comment by eliadevito** [comment]
@tamasmeszaros can you please take a look at this patch and give me a feedback? IMO it can be helpful in upstream.

**Comment by eliadevito** [comment]
@xarbit this fix bug #55 for me and is ready to be merged if for you are ok, maybe we can wait for feedback from @tamasmeszaros and @friedelwolff before merge this

**Comment by xarbit** [comment]
@eliadevito thats awesome, i think we can merge it never the less. But lets give @friedelwolff a bit to confirm that it is solved. 
To me it looks like this could be a fix for upstream, so we should create a MR there also and remove the patch once it is merged for the next release.. What do you think?

**Comment by eliadevito** [comment]
Hi @xarbit,
sorry for the long delay in replying, as mentioned on the upstream [issue](https://github.com/prusa3d/PrusaSlicer/issues/9334) this change is already part of upstream master branch so if you agree I think that this can be merged until PrusaSlicer 2.6 will not be released.

**Comment by xarbit** [comment]
ok, thanks for letting me know. Will do

**Pull request merged**
