### PR TITLE
add support for flatpak in  perform_downloader_desktop_integration

### PR DESCRIPTION
**Pull request by eliadevito**
Hi @xarbit,
This should fix https://github.com/flathub/com.prusa3d.PrusaSlicer/issues/81, if it work i will send a pull request upstream for merge

### CODE REVIEW

**Comment by xarbit** [comment]
for some reason the builds fail

**Comment by eliadevito** [comment]
seem related to recent upstream commits, tomorrow i investigate better and open an issue upstream

**Comment by eliadevito** [comment]
this commit should fix this build error

```
/run/build/PrusaSlicer/src/libslic3r/CutUtils.cpp: In member function ‘const ModelObjectPtrs& Slic3r::Cut::perform_with_plane()’:
/run/build/PrusaSlicer/src/libslic3r/CutUtils.cpp:300:23: error: ‘trace’ was not declared in this scope
  300 |     BOOST_LOG_TRIVIAL(trace) << "ModelObject::cut - start";
      |                       ^~~~~
/run/build/PrusaSlicer/src/libslic3r/CutUtils.cpp:300:5: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
  300 |     BOOST_LOG_TRIVIAL(trace) << "ModelObject::cut - start";
      |     ^~~~~~~~~~~~~~~~~
```

remain only the tbb error, now i’ll take a look

**Comment by eliadevito** [comment]
ok the boost error is gone, try tbb fix :crossed_fingers:

**Comment by eliadevito** [comment]
the x86_64 build seems OK, I sended upstream a PR to add missing includes, after tests (probably tomorrow) i will send another PR with the patch to fix printables desktop integration

**Comment by xarbit** [comment]
Hi @eliadevito 
Great job .. That's a bunch of patches needed .. 

What do we do with this PR? Are you getting this upstreamed and we ignore or can I merge this?

Thanks!

**Comment by xarbit** [comment]
https://github.com/prusa3d/PrusaSlicer/pull/11218

**Comment by xarbit** [comment]
That's fine, let's wait for your minor changes in the printable integration patch. 
We should also integrate the changes needed for the printables.com appurl mime type upstream.

**Comment by eliadevito** [comment]
Hi @xarbit,
we are ready, after finish this build can be pushed in beta.

I sended printables.com integration patch upstream (https://github.com/prusa3d/PrusaSlicer/pull/11229)

**Pull request merged**
