### PR TITLE
Add x-checker for openssl

### PR DESCRIPTION
**Pull request by bbhtt**
Openssl is a very security sensitive library, so let's make sure it stays updated automatically. x-checker will open PRs whenever there is a newer version available

### CODE REVIEW

**Comment by xarbit** [comment]
I appreciate your input.

Unfortunately, the proposed solution might not be suitable for us due to our reliance on upstream build tools and scripts. Our approach involves pre-downloading dependencies to the external/ directory and delegating the build process to prusa build tools.

If the pre-downloaded sha256 doesn't match the upstream cmake, it could lead to build failures. To address this, it would be necessary for Upstream (Prusa3D) to manage these updates.

While we understand the alternative approach you suggest, adopting it would require us to modify the manifest, including building OpenSSL ourselves and ensuring its maintenance.

**Comment by bbhtt** [comment]
> While we understand the alternative approach you suggest, adopting it would require us to modify the manifest, including building OpenSSL ourselves and ensuring its maintenance.

Aren't you already building it here? Maybe it would be possible to decouple openssl build from the prusaslicer module and install it before that?

**Comment by xarbit** [comment]
Certainly, it's feasible to separate the OpenSSL build from the PrusaSlicer module.

However, our aim is to closely follow the upstream version, mirroring the Prusa team's tested releases. 

To update this module, it's advisable to work on updating it upstream. For security matters, please raise a ticket with PrusaSlicer, as they would need to address it in their packaging and release cycle too, we would benefit from it as well.

Our responsibility here is solely for the flatpak packaging, following PrusaSlicer cycle.

Hope this is understandable?

**Comment by bbhtt** [comment]
https://github.com/prusa3d/PrusaSlicer/issues/11193

**Pull request closed without merging**
