### PR TITLE
Upgrade to 2.6.0-alpha4

### PR DESCRIPTION
**Pull request by eliadevito**
build 2.6.0-alpha4

### CODE REVIEW

**Comment by xarbit** [comment]
since PrusaSlicer updated wxWidgets, can you please also verify if Wayland works?

**Comment by eliadevito** [comment]
Simply adding --socket=wayland doesn't work, prusa-slicer force X11 [here](https://github.com/prusa3d/PrusaSlicer/blob/4199d1aef6d626f2c343954313c2522901b852ad/src/PrusaSlicer.cpp#L82).
I will make a patched build to test if it work

**Comment by xarbit** [comment]
@eliadevito please see this: 
https://github.com/prusa3d/PrusaSlicer/issues/9776#issuecomment-1438169165 

It seems it might still be useless to try wayland .. @tamasmeszaros already tried and opened an issue on wxWidgets
Which would be a bummer ..

**Comment by eliadevito** [comment]
@xarbit this build seem to works without issue, if for you are ok it could be released as beta to allow flatpak users to test the new version

**Pull request merged**
