### PR TITLE
Bump 2.5.0 (hopefully :-))

### PR DESCRIPTION
**Pull request by eliadevito**
This should build without failure.

I added a patch to disable lto flag during build as a suggested by @tamasmeszaros  here https://github.com/prusa3d/PrusaSlicer/issues/8922#issuecomment-1265276168, and setted the runtime version to 21.08 to fix a new error that came out with the patched TTB.

### CODE REVIEW

**Comment by eliadevito** [comment]
bot, build com.prusa3d.PrusaSlicer

**Comment by eliadevito** [comment]
> Build [973 successful](https://buildbot.flathub.org/#/builders/6/builds/973) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/113419/com.prusa3d.PrusaSlicer.flatpakref
> ```

this start but crash during slice i make another try

**Comment by xarbit** [comment]
@eliadevito let me know if you tested this build and when it is ready .. great job and thanks!

**Comment by bubnikv** [comment]
@eliadevito do you have any details on the umount patch? Why does umount not work?

**Comment by eliadevito** [comment]
> @eliadevito let me know if you tested this build and when it is ready .. great job and thanks!

actually they continue to crash during slice, It should be related to tbb. 

I think that there is a tbb/gcc quirk that don't appears on official builds because devtools-10 on centos 7 has lot patches applied and some of these probably prevent crash.

I will keep you updated

**Comment by eliadevito** [comment]
> @eliadevito do you have any details on the umount patch? Why does umount not work?

I don't have tested it yet, the appimages version works without problem, the flatpak version return a generic error in UI and this in the terminal: [0x00007f33549069c0] [error]   Ejecting failed. Exit code: 32

I will give you more info after I try the patch

**Comment by tamasmeszaros** [comment]
I regularly make builds on Manjaro with latest clang 14 and also with gcc 12. No crash during slicing.

**Comment by tamasmeszaros** [comment]
Hello! After some thorough debugging, the likely cause of the slicing crash was found. We still cannot directly reproduce the crash, but there is a very good chance that the following branch will fix it: Check out [lh_master_250_flatpak](https://github.com/prusa3d/PrusaSlicer/tree/lh_master_250_flatpak).

**Comment by eliadevito** [comment]
> Hello! After some thorough debugging, the likely cause of the slicing crash was found. We still cannot directly reproduce the crash, but there is a very good chance that the following branch will fix it: Check out [lh_master_250_flatpak](https://github.com/prusa3d/PrusaSlicer/tree/lh_master_250_flatpak).

Hello, thanks a lot for the work, I will try it on now

**Comment by eliadevito** [comment]
@tamasmeszaros I confirm you that the branch lh_master_250_flatpak fixes the crash on slice, thanks a lot!

There is a crash when i try to umount external device but this most likely caused by the patch from snap

**Pull request merged**
