### PR TITLE
bump version 2.7.3

### PR DESCRIPTION
**Pull request by eliadevito**

### CODE REVIEW

**Comment by lbrunkho** [comment]
Confirmed that build 110793 installs and runs as expected.

**Comment by xarbit** [comment]
Is this ready? @eliadevito

**Comment by eliadevito** [comment]
> Is this ready? @eliadevito

The 110793 build has a bug the printables.com downloads integration (https://github.com/prusa3d/PrusaSlicer/pull/12252#issuecomment-2024900154).

Now I added new build with a potential fix for this.

**Comment by eliadevito** [comment]
@xarbit ready for merge

**Pull request merged**
