### PR TITLE
add changelog of Prusaslicer 2.6.0

### PR DESCRIPTION
**Pull request by eliadevito**
this adds a list of changes and the url to the detailed changelog on the Prusaslicer website

### CODE REVIEW

**Comment by eliadevito** [comment]
Hi @xarbit , if you are OK with the change this can be merged

**Comment by xarbit** [comment]
Hi @eliadevito ,

I'm basically ok with this .. I actually did that in the past when I created this repo. 
But honestly, after a few iterations it involved some work and time to keep Prusa's large change logs updated and consistent to make sense. 
Is this something you really want to do and take care of? 

We could just add the url which contains the full change log. 

But if you are willing to keep this info up to date, im fine with it.

**Comment by xarbit** [comment]
@eliadevito any update on this?

**Comment by xarbit** [comment]
Awesome! Thx

**Pull request merged**
